# Generated by Django 5.2.4 on 2025-08-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_car_speed_alter_car_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.ImageField(default=50, upload_to=''),
        ),
    ]
