# Generated by Django 5.2.4 on 2025-10-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_receipe_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipe',
            options={'ordering': ['receipe_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
